Repository dfusiontech/dfusiontech-site-angular-6, pull requests merged in 2018-08, with the labels that each got.

#7 dft-btn
  angular.json
  src/less/components/dft-btn.less
  src/less/index.less
Labels: enhancement

#8 Changed base typing rules
  src/app/states/home/home.html
  src/assets/fonts/dft-icon-font/dft-icon-font.eot
  src/assets/fonts/dft-icon-font/dft-icon-font.svg
  src/assets/fonts/dft-icon-font/dft-icon-font.ttf
  src/assets/fonts/dft-icon-font/dft-icon-font.woff
  src/assets/fonts/dft-icon-font/dft-icon-font.woff2
  src/assets/fonts/dft-icon-font/selection.json
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.eot
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.otf
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.svg
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.ttf
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.woff
  src/assets/fonts/grotesk/bold/HKGrotesk-Bold.woff2
  src/assets/fonts/grotesk/bold/HKGrotesk-Light.eot
  src/assets/fonts/grotesk/bold/HKGrotesk-Light.svg
  src/assets/fonts/grotesk/bold/HKGrotesk-Light.ttf
  src/assets/fonts/grotesk/bold/HKGrotesk-Light.woff
  src/assets/fonts/grotesk/bold/HKGrotesk-Light.woff2
  src/assets/fonts/grotesk/light/HKGrotesk-Light.eot
  src/assets/fonts/grotesk/light/HKGrotesk-Light.otf
  src/assets/fonts/grotesk/light/HKGrotesk-Light.svg
  src/assets/fonts/grotesk/light/HKGrotesk-Light.ttf
  src/assets/fonts/grotesk/light/HKGrotesk-Light.woff
  src/assets/fonts/grotesk/light/HKGrotesk-Light.woff2
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.eot
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.otf
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.svg
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.ttf
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.woff
  src/assets/fonts/grotesk/medium/HKGrotesk-Medium.woff2
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.eot
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.otf
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.svg
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.ttf
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.woff
  src/assets/fonts/grotesk/regular/HKGrotesk-Regular.woff2
  src/assets/fonts/grotesk/semi-bold-italic/HKGrotesk-SemiBoldItalic.eot
  src/assets/fonts/grotesk/semi-bold-italic/HKGrotesk-SemiBoldItalic.svg
  src/assets/fonts/grotesk/semi-bold-italic/HKGrotesk-SemiBoldItalic.ttf
  src/assets/fonts/grotesk/semi-bold-italic/HKGrotesk-SemiBoldItalic.woff
  src/assets/fonts/grotesk/semi-bold-italic/HKGrotesk-SemiBoldItalic.woff2
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.eot
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.otf
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.svg
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.ttf
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.woff
  src/assets/fonts/grotesk/semi-bold/HKGrotesk-SemiBold.woff2
  src/less/index.less
  src/less/layout.less
  src/less/theme/fonts.less
  src/less/theme/fonts/_dft-icon-font-variables.less
  src/less/theme/fonts/dft-icon-font.less
  src/less/theme/fonts/grotesk-font-family.less
  src/less/theme/typing.less
  src/less/variables.less
Labels: enhancement

#9 Features/footer
  src/app/app.module.ts
  src/app/components/footer/footer.component.ts
  src/app/components/footer/footer.html
  src/app/states/home/home.page.ts
  src/app/states/layout.html
  src/app/states/layout.module.ts
  src/assets/fonts/extraGlyphClutch/clutch-icon.eot
  src/assets/fonts/extraGlyphClutch/clutch-icon.svg
  src/assets/fonts/extraGlyphClutch/clutch-icon.ttf
  src/assets/fonts/extraGlyphClutch/clutch-icon.woff
  src/assets/fonts/extraGlyphClutch/clutch-icon.woff2
  src/assets/fonts/grotesk/bold/font.css
  src/assets/fonts/grotesk/light/font.css
  src/assets/fonts/grotesk/medium/font.css
  src/assets/fonts/grotesk/regular/font.css
  src/assets/fonts/grotesk/semi-bold/font.css
  src/less/components/footer.less
  src/less/extra-icons/clutch.less
  src/less/index.less
  src/less/layout.less
  src/less/theme/grotesk-font-family.less
  src/less/variables.less
Labels: enhancement

#14 Features/pages.tree
  src/app/states/layout.html
  src/index.html
  src/less/extra-icons/clutch.less
  src/less/index.less
  src/less/pages/about-us.page.less
  src/less/pages/cases-item.page.less
  src/less/pages/cases.page.less
  src/less/pages/contacts.page.less
  src/less/pages/home.page.less
  src/less/pages/thoughts-item.page.less
  src/less/pages/thoughts.page.less
Labels: enhancement

#15 Hotfix/after.merging
  src/app/components/footer/footer.html
  src/less/theme/fonts/dft-icon-font.less
Labels: fix

#13 features/header
  package-lock.json
  package.json
  src/app/components/header/header.component.ts
  src/app/components/header/header.html
  src/app/states/about-us/about-us.state.ts
  src/app/states/case-item/cases-item.state.ts
  src/app/states/cases/cases.state.ts
  src/app/states/contacts/contacts.state.ts
  src/app/states/home/home.state.ts
  src/app/states/layout.component.ts
  src/app/states/layout.html
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
  src/app/states/thoughts/thoughts.state.ts
  src/assets/images/dft-logo.png
  src/assets/images/mobile-logo.png
  src/less/components/dft-link.less
  src/less/components/header.less
  src/less/index.less
  src/less/layout.less
  src/less/theme/links.less
Labels: enhancement

#16 Features/bg.lines
  src/app/components/footer/footer.html
  src/app/states/layout.html
  src/less/components/footer.less
  src/less/layout.less
Labels: enhancement

#17 added some dft-arrow-icons
  src/assets/fonts/dft-icon-font/dft-icon-font.eot
  src/assets/fonts/dft-icon-font/dft-icon-font.svg
  src/assets/fonts/dft-icon-font/dft-icon-font.ttf
  src/assets/fonts/dft-icon-font/dft-icon-font.woff
  src/assets/fonts/dft-icon-font/dft-icon-font.woff2
  src/assets/fonts/dft-icon-font/selection.json
  src/less/theme/fonts/_dft-icon-font-variables.less
  src/less/theme/fonts/dft-icon-font.less
Labels: enhancement

#19 Features/contacts.page
  package-lock.json
  package.json
  src/app/states/contacts/contacts.html
  src/app/states/layout.module.ts
  src/less/components/dft-btn.less
  src/less/layout.less
  src/less/pages/contacts.page.less
  src/less/variables.less
Labels: enhancement

#18 hotfix/header
  src/app/components/header/header.component.ts
  src/app/components/header/header.html
  src/app/states/layout.module.ts
  src/less/components/header.less
  src/less/layout.less
  src/less/variables.less
Labels: fix

#20 Features/contacts.page
  package-lock.json
  src/app/states/contacts/contacts.html
  src/app/states/contacts/contacts.page.ts
  src/app/states/home/home.html
  src/less/components/decorators.less
  src/less/components/header.less
  src/less/components/page-heading.less
  src/less/index.less
  src/less/layout.less
  src/less/pages/contacts.page.less
  src/less/pages/home.page.less
Labels: enhancement, fix

#22 Features/thoughts.page
  src/app/states/contacts/contacts.html
  src/app/states/home/home.html
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
  src/assets/images/thoughts-page/business-1.png
  src/assets/images/thoughts-page/business-2.png
  src/assets/images/thoughts-page/heading-bg.png
  src/assets/images/thoughts-page/lincoln-center-1.png
  src/assets/images/thoughts-page/lincoln-center-2.png
  src/assets/images/thoughts-page/lincoln-center-3.png
  src/assets/images/thoughts-page/story-1.png
  src/assets/images/thoughts-page/story-2.png
  src/less/components/decorators.less
  src/less/components/page-heading.less
  src/less/pages/thoughts.page.less
  src/less/theme/typing.less
Labels: enhancement, fix

#23 Features/thoughts item.page
  src/app/states/thoughts-item/thoughts-item.html
  src/assets/fonts/dft-icon-font/dft-icon-font.eot
  src/assets/fonts/dft-icon-font/dft-icon-font.svg
  src/assets/fonts/dft-icon-font/dft-icon-font.ttf
  src/assets/fonts/dft-icon-font/dft-icon-font.woff
  src/assets/fonts/dft-icon-font/dft-icon-font.woff2
  src/assets/fonts/dft-icon-font/selection.json
  src/assets/images/thoughts-item-page/Bitmap.png
  src/less/components/decorators.less
  src/less/components/page-heading.less
  src/less/pages/thoughts-item.page.less
  src/less/theme/fonts/_dft-icon-font-variables.less
  src/less/theme/fonts/dft-icon-font.less
Labels: enhancement, fix

#24 Hotfix/after.merging
  src/app/components/header/header.html
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts/thoughts.html
  src/less/components/date.less
  src/less/components/decorators.less
  src/less/components/dft-list.less
  src/less/components/grey-rectangle.less
  src/less/components/header.less
  src/less/components/horizontal-line.less
  src/less/components/paragraph.less
  src/less/components/quote-signs.less
  src/less/index.less
  src/less/pages/thoughts-item.page.less
Labels: enhancement, fix

#27 Features/case page
  src/app/states/case/case-page.html
  src/app/states/case/case.page.ts
  src/assets/images/pages/case-page/screenshot-project-1.jpg
  src/assets/images/pages/case-page/screenshot-project-2.jpg
  src/assets/images/pages/case-page/technology-stack/AWS.png
  src/assets/images/pages/case-page/technology-stack/FFmpeg.png
  src/assets/images/pages/case-page/technology-stack/Java.png
  src/assets/images/pages/case-page/technology-stack/Mockito.png
  src/assets/images/pages/case-page/technology-stack/Node.png
  src/assets/images/pages/case-page/technology-stack/algolia.png
  src/assets/images/pages/case-page/technology-stack/angular.png
  src/assets/images/pages/case-page/technology-stack/api-google.png
  src/assets/images/pages/case-page/technology-stack/bootstrap.png
  src/assets/images/pages/case-page/technology-stack/express.png
  src/assets/images/pages/case-page/technology-stack/jUnit.png
  src/assets/images/pages/case-page/technology-stack/jra.png
  src/assets/images/pages/case-page/technology-stack/mongoose.png
  src/assets/images/pages/case-page/technology-stack/prediction.png
  src/assets/images/pages/case-page/technology-stack/rabbitmq.png
  src/assets/images/pages/case-page/technology-stack/restfb.png
  src/assets/images/pages/case-page/technology-stack/spring.png
  src/assets/images/pages/case-page/technology-stack/swagger.png
  src/assets/images/pages/case-page/technology-stack/ui.png
  src/assets/images/pages/case-page/unreel.me.jpg
  src/less/pages/case.page.less
Labels: enhancement

#28 Features/about us.page
  src/app/states/about-us/about-us.html
  src/assets/images/pages/about-us/advantage1-md.png
  src/assets/images/pages/about-us/advantage1.png
  src/assets/images/pages/about-us/advantage2-md.png
  src/assets/images/pages/about-us/advantage2.png
  src/assets/images/pages/about-us/advantage3-md.png
  src/assets/images/pages/about-us/advantage3.png
  src/assets/images/pages/about-us/heading-bg.png
  src/assets/images/pages/about-us/leaders/Eugene.png
  src/assets/images/pages/about-us/leaders/Igor.png
  src/assets/images/pages/about-us/leaders/Marina.png
  src/assets/images/pages/about-us/leaders/Oleg.png
  src/assets/images/pages/about-us/leaders/Sergey.png
  src/assets/images/pages/about-us/leaders/Vadim.png
  src/less/components/grey-rectangle.less
  src/less/components/layout-helpers.less
  src/less/components/page-heading.less
  src/less/index.less
  src/less/pages/about-us.page.less
  src/less/pages/thoughts-item.page.less
  src/less/variables.less
Labels: bug, enhancement

#29 Features/home.page
  src/app/states/case/case.page.ts
  src/app/states/home/home.html
  src/app/states/home/home.page.ts
  src/less/pages/home.page.less
Labels: enhancement

#30 Problem with build resolved.
  src/app/components/lets-chat/lets-chat.component.ts
  src/app/components/lets-chat/lets-chat.html
  src/app/states/layout.module.ts
Labels: fix

#33 Features/development
  angular.json
  package-lock.json
  package.json
  src/app/constants/thoughts.constant.ts
  src/app/models/thought.model.ts
  src/app/services/Thoughts.service.ts
  src/app/states/about-us/about-us.html
  src/app/states/case/case-page.html
  src/app/states/cases/cases.html
  src/app/states/cases/cases.page.ts
  src/app/states/home/home.html
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
  src/less/components/footer.less
  src/less/components/grey-headline.less
  src/less/components/grey-rectangle.less
  src/less/components/lets-chat.less
  src/less/index.less
  src/less/pages/about-us.page.less
  src/less/pages/case.page.less
  src/less/pages/cases.page.less
  src/less/pages/contacts.page.less
  src/less/pages/home.page.less
  src/less/theme/fonts/_dft-icon-font-variables.less
  src/less/theme/fonts/dft-icon-font.less
  src/less/theme/fonts/grotesk-font-family.less
  src/less/variables.less
Labels: enhancement, fix

#34 Features/team.leaders.upgrade
  package-lock.json
  src/app/states/about-us/about-us.html
  src/app/states/about-us/about-us.page.ts
  src/assets/images/pages/about-us/leaders/eugene.png
  src/assets/images/pages/about-us/leaders/igor.png
  src/assets/images/pages/about-us/leaders/marina.png
  src/assets/images/pages/about-us/leaders/oleg.png
  src/assets/images/pages/about-us/leaders/sergey.png
  src/assets/images/pages/about-us/leaders/vadim.png
  src/less/mixins.less
  src/less/pages/about-us.page.less
Labels: enhancement

#35 Form Validation
  angular.json
  src/app/states/contacts/contacts.html
  src/app/states/contacts/contacts.page.ts
  src/app/states/layout.module.ts
  src/less/components/dft-btn.less
  src/less/index.less
  src/less/pages/contacts.page.less
  src/less/theme/fonts/_dft-icon-font-variables.less
  src/less/variables.less
Labels: enhancement, fix
