Repository dfusiontech/dfusiontech-site-angular-6, pull requests merged in 2018-11, with the labels that each got.

#55 Hotfix/after.third.release
  src/app/states/about-us/about-us.html
  src/app/states/about-us/about-us.page.ts
  src/app/states/case/case-page.html
  src/app/states/case/case.page.ts
  src/app/states/cases/cases.html
  src/app/states/cases/cases.page.ts
  src/app/states/contacts/contacts.html
  src/app/states/contacts/contacts.page.ts
  src/app/states/home/home.html
  src/app/states/home/home.page.ts
  src/app/states/layout.component.ts
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
  src/index.html
  src/less/pages/thoughts-item.page.less
Labels: fix

#60 Header animation and transition mixins
  src/app/app.module.ts
  src/less/components/dft-btn.less
  src/less/components/footer.less
  src/less/components/grey-rectangle.less
  src/less/components/header.less
  src/less/components/page-heading.less
  src/less/mixins.less
  src/less/pages/about-us.page.less
  src/less/pages/cases.page.less
  src/less/pages/contacts.page.less
  src/less/pages/home.page.less
  src/less/pages/thoughts-item.page.less
  src/less/pages/thoughts.page.less
Labels: enhancement, fix

#61 Features/projects content
  src/app/constants/cases.constant.ts
  src/app/models/case.model.ts
  src/app/services/Cases.service.ts
  src/app/states/case/case-page.html
  src/app/states/case/case-page.state.ts
  src/app/states/cases/cases.html
  src/app/states/home/home.html
  src/assets/images/pages/case-page/almentor/courses-arabic-version.jpg
  src/assets/images/pages/case-page/almentor/courses-en-version.jpg
  src/assets/images/pages/case-page/almentor/heading.jpg
  src/assets/images/pages/case-page/bottles-waiting/DJ-version.jpg
  src/assets/images/pages/case-page/bottles-waiting/heading.jpg
  src/assets/images/pages/case-page/bottles-waiting/nightlife.jpg
  src/assets/images/pages/case-page/flaskdata/about-flask.jpg
  src/assets/images/pages/case-page/flaskdata/heading.jpg
  src/assets/images/pages/case-page/flaskdata/products-flask.jpg
  src/assets/images/pages/case-page/lincoln-center/heading.jpg
  src/assets/images/pages/case-page/lincoln-center/score-lincoln-center.jpg
  src/assets/images/pages/case-page/lincoln-center/video-lincoln-center.jpg
  src/assets/images/pages/case-page/screenshot-project-1.jpg
  src/assets/images/pages/case-page/screenshot-project-2.jpg
  src/assets/images/pages/case-page/skillz/about-skillz.jpg
  src/assets/images/pages/case-page/skillz/heading.jpg
  src/assets/images/pages/case-page/skillz/products-skillz.jpg
  src/assets/images/pages/case-page/technology-stack/angular-js.png
  src/assets/images/pages/case-page/technology-stack/angular-ui-router.png
  src/assets/images/pages/case-page/technology-stack/jraw.png
  src/assets/images/pages/case-page/technology-stack/node-js.png
  src/assets/images/pages/case-page/technology-stack/predictionIO.png
  src/assets/images/pages/case-page/unreel-me/about-unreel-me.jpg
  src/assets/images/pages/case-page/unreel-me/heading.jpg
  src/assets/images/pages/case-page/unreel-me/product-unreel-me.jpg
  src/assets/images/pages/case-page/unreel.me.jpg
  src/assets/images/pages/cases/almentor.jpg
  src/assets/images/pages/cases/bottles-waiting.jpg
  src/assets/images/pages/cases/codefresh.jpg
  src/assets/images/pages/cases/flaskdata.jpg
  src/assets/images/pages/cases/lincoln-center.jpg
  src/assets/images/pages/cases/skillz.jpg
  src/assets/images/pages/cases/unreel-me.jpg
  src/assets/images/pages/cases/worldtv.jpg
  src/less/pages/cases.page.less
  src/less/pages/home.page.less
Labels: enhancement

#62 [+] SEOService implemented;
  src/app/app.module.ts
  src/app/services/Seo.service.ts
  src/app/states/about-us/about-us.page.ts
  src/app/states/case/case.page.ts
  src/app/states/cases/cases.page.ts
  src/app/states/contacts/contacts.page.ts
  src/app/states/home/home.page.ts
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts/thoughts.page.ts
Labels: enhancement
