Repository dfusiontech/dfusiontech-site-angular-6, pull requests merged in 2018-09, with the labels that each got.

#37 Features/team.leaders.upgrade
  src/app/components/lets-chat/lets-chat.html
  src/app/states/about-us/about-us.html
  src/app/states/contacts/contacts.html
  src/less/components/dft-btn.less
  src/less/pages/about-us.page.less
Labels: enhancement

#42 Features/cases.home.dynamic
  src/app/constants/cases.constant.ts
  src/app/models/case.model.ts
  src/app/services/Cases.service.ts
  src/app/states/case/case-page.state.ts
  src/app/states/cases/cases.html
  src/app/states/cases/cases.page.ts
  src/app/states/home/home.html
Labels: enhancement

#43 Fix fa font path
  src/less/variables.less
Labels: enhancement, fix

#39 Features/contacts.page
  src/app/states/contacts/contacts.html
  src/less/components/decorators.less
  src/less/components/page-heading.less
  src/less/pages/contacts.page.less
Labels: fix

#44 Features/thoughts.router.params
  src/app/services/Thoughts.service.ts
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
Labels: enhancement

#45 Features/thoughts.router.params
  src/app/states/thoughts-item/thoughts-item.state.ts
Labels: enhancement, fix

#46 Update Angular 6.1.5 -> 6.2.1
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/services/Cases.service.ts
  src/app/services/Thoughts.service.ts
  src/app/states/about-us/about-us.page.ts
  src/app/states/about-us/about-us.state.ts
  src/app/states/case/case-page.state.ts
  src/app/states/case/case.page.ts
  src/app/states/cases/cases.page.ts
  src/app/states/cases/cases.state.ts
  src/app/states/contacts/contacts.state.ts
  src/app/states/home/home.page.ts
  src/app/states/home/home.state.ts
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
  src/app/states/thoughts/thoughts.page.ts
  src/app/states/thoughts/thoughts.state.ts
  src/browserslist
  src/main.ts
  src/tsconfig.app.json
  tslint.json
Labels: enhancement, fix

#48 Features/cases.router.params
  src/app/constants/cases.constant.ts
  src/app/services/Cases.service.ts
  src/app/services/Thoughts.service.ts
  src/app/states/case/case-page.html
  src/app/states/case/case-page.state.ts
  src/app/states/case/case.page.ts
  src/app/states/cases/cases.html
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
Labels: enhancement

#49 Features/cases.router.params
  src/app/states/case/case.page.ts
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
Labels: enhancement

#50 Features/components.review
  src/app/components/lets-chat/lets-chat.html
  src/app/components/preloader/preloader.component.ts
  src/app/components/preloader/preloader.html
  src/app/states/cases/cases.html
  src/app/states/cases/cases.page.ts
  src/app/states/cases/cases.state.ts
  src/app/states/contacts/contacts.page.ts
  src/app/states/contacts/contacts.state.ts
  src/app/states/home/home.html
  src/app/states/layout.html
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
  src/app/states/thoughts/thoughts.state.ts
  src/index.html
  src/less/components/lets-chat.less
  src/less/components/preloader.less
  src/less/pages/home.page.less
Labels: enhancement, fix

#52 Hotfix/components.review.vs.resolve.tslint
  src/app/components/error-message/error-message.component.ts
  src/app/components/footer/footer.component.ts
  src/app/components/footer/footer.html
  src/app/components/header/header.component.ts
  src/app/components/header/header.html
  src/app/components/lets-chat/lets-chat.component.ts
  src/app/components/preloader/preloader.component.ts
  src/app/constants/cases.constant.ts
  src/app/services/Cases.service.ts
  src/app/states/about-us/about-us.html
  src/app/states/about-us/about-us.page.ts
  src/app/states/about-us/about-us.state.ts
  src/app/states/case/case-page.html
  src/app/states/case/case-page.state.ts
  src/app/states/case/case.page.ts
  src/app/states/cases/cases.html
  src/app/states/cases/cases.page.ts
  src/app/states/cases/cases.state.ts
  src/app/states/contacts/contacts.html
  src/app/states/contacts/contacts.page.ts
  src/app/states/contacts/contacts.state.ts
  src/app/states/home/home.html
  src/app/states/home/home.page.ts
  src/app/states/home/home.state.ts
  src/app/states/layout.component.ts
  src/app/states/layout.html
  src/app/states/layout.module.ts
  src/app/states/thoughts-item/thoughts-item.html
  src/app/states/thoughts-item/thoughts-item.page.ts
  src/app/states/thoughts-item/thoughts-item.state.ts
  src/app/states/thoughts/thoughts.html
  src/app/states/thoughts/thoughts.page.ts
  src/app/states/thoughts/thoughts.state.ts
  src/index.html
  src/less/pages/about-us.page.less
  src/main.ts
  src/tests/app.spec.ts
  src/tslint.json
Labels: fix
